on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    name: release-please-action
    uses: google-github-actions/release-please-action@v4.1.0
